### ISSUE TITLE
worldCheck.py does not check for valid score changes

### ISSUE THREAD

**Issue by sarnsdev** [DeaconSeals/GPacFormatCheck#1]
While trying to break your checking script I found that there is no check on the way the score changes. As is, world files are still seen as valid even if the score decrements which based on the game rules is not possible. For example, the following is said the be a valid world: 

...
m 4 12
1 29 2
2 29 4
3 26 13
t 1259 7 <-------- score has been increasing or staying constant up to this
m 4 11
1 29 1
2 29 3
3 25 13
t 1258 200 <-------- notice the rapid change in score 
m 4 10
1 29 2
2 29 2
3 26 13
t 1257 7 <--------- then it plummets (which should be invalid)
...

**Comment by DeaconSeals** [comment]
This was a feature I originally opted not to add. The purpose of this tool is not to guarantee the absolute correctness of the world files, but rather to highlight and provide feedback on common formatting mistakes. In other words, all of the existing checks for simulation correctness are additional features outside original project scope.

I have added a check for decrementing score, but tracking absolutely correct score tracking from the world file involves inferring fruit value; identifying game endings; and considering a wealth of edge cases relating to fruit spawn, action order, and game endings. While many of those capabilities are tentatively planned features for this project, they are indeed stretch goals at this time. There are also consequences for considering score beyond development overhead. In particular, throwing error messages on decrementing score prevents the validation of world files that investigate evolution in scenarios with negative fruit cost. Those files will not cause the checker to halt, but the error messages will now require more manual parsing.
