### ISSUE TITLE
Pill Constraint

### ISSUE THREAD

**Issue by BradleyMorgan** [DeaconSeals/GPacFormatCheck#2]
The pill spawn check barks when a pill is placed in a ghost location, which I don't think is a constraint--at least I didn't see it in the docs.  (Line 326 in worldCheck.py).   Thanks!

`				if location in [loc for player in movingLocations for loc in movingLocations[player]]: # you spawned on someone
					errors.append("pill spawned onto a player at location "+repr(location)+" on line "+repr(line+1))`

**Comment by DeaconSeals** [comment]
I didn't see this issue, but just pushed a fix for this! I mistakenly thought that the pills couldn't spawn in either of the starting locations, but this has now been resolved.
